### ISSUE TITLE
Error("HeapOther(\"I/O Error: No such file or directory (os error 2)\")")

### ISSUE THREAD

**Issue by adals** [bzar/webchat-rs#2]
make run
~/.cargo/bin/wasm-bindgen target/wasm32-unknown-unknown/debug/webchat_client_rs.wasm --out-dir web
thread 'main' panicked at 'failed to generate bindings: Error("HeapOther(\"I/O Error: No such file or directory (os error 2)\")")', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

my system is macOs

**Comment by bzar** [comment]
Hm, seems like an error within wasm-bindgen. You did run this inside the webchat-client-rs subdirectory, right?

**Comment by bzar** [comment]
Okay, found the issue. Fixed by 855efb9

**Comment by adals** [comment]
thanks 
it does work right now
