### ISSUE TITLE
Does not work with chromium 65

### ISSUE THREAD

**Issue by flosse** [bzar/webchat-rs#3]
`Uncaught (in promise) RangeError: WebAssembly.Instance is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.instantiate.`

**Comment by bzar** [comment]
Yes, this is due to what is believed to be a bug in webpack: https://github.com/rustwasm/wasm-bindgen/blob/master/examples/hello_world/README.md#caveat-for-chrome-users
I'll amend the README
